package com.bhf.aeroncache.models;

public enum BulkOperationType {
    NONE,
    CREATE_CACHE,
    ADD_ITEM,
    REMOVE_ITEM,
    CLEAR_CACHE,
    GET_ITEM,
    DELETE_CACHE,
    PATCH_ITEM,
    CREATE_COUNTER_CACHE,
    ADD_COUNTER,
    REMOVE_COUNTER,
    CLEAR_COUNTER_CACHE,
    GET_COUNTER,
    DELETE_COUNTER_CACHE,
    INCREMENT_COUNTER,
    DECREMENT_COUNTER,
    SET_COUNTER,
    CANCEL_ITEM,
    CANCEL_COUNTER
}
