openapi: 3.0.1
info:
  title: Aeron Cache HTTP API
  description: This API exposes endpoints to interact with Aeron Cache.
  termsOfService: https://www.github.com/bhf
  contact:
    name: Sanjeev
    url: https://www.sanjeev.pages.dev
    email: na@na.com
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/
  version: '1.0'
servers:
  - url: http://localhost:7070
    description: Dev server
paths:
  /api/v1/cache:
    post:
      tags:
        - CreateCache
      summary: Create a new cache
      description: Create a cache by specifying the cache Id in the request body
      operationId: createCache
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CreateResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/cache/{cacheId}:
    post:
      tags:
        - PutItem
      summary: Put an item into a cache
      description: Put an item on the specified key into the specified cache
      operationId: putItem
      parameters:
        - name: cacheId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the cache
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutItemRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PutItemResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - DeleteCache
      summary: Delete a cache
      description: Delete the cache specified by it's Id
      operationId: deleteCache
      parameters:
        - name: cacheId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the cache
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DeleteCacheResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/cache/{cacheId}/{key}:
    get:
      tags:
        - GetItem
      summary: Get an item from a cache
      description: Get an item by it's key from the specified cache
      operationId: getItem
      parameters:
        - name: cacheId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the cache
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: The key of the item
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GetItemResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - DeleteItem
      summary: Delete an item from a cache
      description: Delete an item by it's key from the specified cache
      operationId: deleteItem
      parameters:
        - name: cacheId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the cache
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: The key of the item
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DeleteItemResponse'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errorMsg:
          type: string
          example: 'Details about the error that occurred'
        helpMsg:
          type: string
          example: 'A user friendly help message'
    CreateRequest:
      type: object
      properties:
        cacheId:
          type: string
          example: "SomeCacheID"
    CreateResponse:
      type: object
      properties:
        cacheId:
          type: integer
          format: int64
          example: 1
    PutItemRequest:
      type: object
      properties:
        cacheId:
          type: string
          example: "SomeCacheID"
        key:
          type: string
          example: 'SomeRandomKey'
        value:
          type: string
          example: 'SomeRandomValue'
    PutItemResponse:
      type: object
      properties:
        cacheId:
          type: string
          example: "SomeCacheID"
        key:
          type: string
          example: 'SomeRandomKey'
    DeleteCacheResponse:
      type: object
      properties:
        cacheId:
          type: string
          example: "SomeCacheID"
    GetItemResponse:
      type: object
      properties:
        cacheId:
          type: string
          example: "SomeCacheID"
        key:
          type: string
          example: 'SomeRandomKey'
        value:
          type: string
          example: 'SomeRandomValue'
    DeleteItemResponse:
      type: object
      properties:
        cacheId:
          type: string
          example: "SomeCacheID"
        key:
          type: string
          example: 'SomeRandomKey'