openapi: 3.0.3
info:
  title: Aeron Cache WebSocket API
  description: WebSocket API for subscribing to Aeron Cache updates.
  version: 1.1.0
servers:
  - url: ws://localhost:7071
    description: Local WebSocket server

paths:
  /api/ws/v1/cache/{cacheId}:
    get:
      summary: Subscribe to a single cache
      description: |
        Establish a WebSocket connection to subscribe to updates for a single cache.

        After the connection is established (HTTP 101), the server sends a stream of
        JSON text messages, each representing a `CacheUpdateEvent` for the specified
        cache.
      parameters:
        - name: cacheId
          in: path
          required: true
          description: The ID of the cache to subscribe to.
          schema:
            type: string
      responses:
        101:
          description: Switching Protocols - WebSocket connection established.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheUpdateEvent'
        400:
          description: Bad Request - Invalid cache ID.
        500:
          description: Internal Server Error - Unable to subscribe to the cache.

  /api/ws/v1/caches/{cacheIds}:
    get:
      summary: Subscribe to multiple caches
      description: |
        Establish a WebSocket connection to subscribe to updates for multiple caches.

        After the connection is established (HTTP 101), the server sends a stream of
        JSON text messages, each representing a `CacheUpdateEvent` for any of the
        subscribed caches.
      parameters:
        - name: cacheIds
          in: path
          required: true
          description: Comma-separated list of cache IDs to subscribe to.
          schema:
            type: string
      responses:
        101:
          description: Switching Protocols - WebSocket connection established.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheUpdateEvent'
        400:
          description: Bad Request - Invalid cache IDs.
        500:
          description: Internal Server Error - Unable to subscribe to the caches.

components:
  schemas:
    CacheUpdateEvent:
      type: object
      description: A cache update event published over the WebSocket connection.
      properties:
        cacheId:
          type: string
          description: The ID of the cache.
        eventType:
          type: string
          description: The type of event.
          enum:
            - ADD_ITEM
            - DELETE_CACHE
            - REMOVE_ITEM
            - CLEAR_CACHE
        itemKey:
          type: string
          nullable: true
          description: The key of the item.
        itemValue:
          type: string
          nullable: true
          description: The value of the item.
        requestId:
          type: string
          description: The request ID associated with the event.
      required:
        - cacheId
        - eventType
        - requestId