java_library(
    name = "client",
    srcs = [
        "src/main/java/com/aeron/cache/client/AeronCacheClient.java",
        "src/main/java/com/aeron/cache/client/EmbeddedAeronCache.java",
    ],
    visibility = ["//visibility:public"],
)
